### Create a new note
POST http://localhost:3000/notes
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYyODU2NzgxLCJleHAiOjE3NjI4OTI3ODF9.jg8H_6XnF5E1brrEyqa50yg0HB1dbByk21BVNmv1cwk; Max-Age=36000; Expires=Tue, 11 Nov 2025 20:26:21 GMT; Path=/; HttpOnly

{
    "name": "xd1223",
    "content": "This is a test note content."
}

### Download note content
GET http://localhost:3000/notes/29
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYxMjA4MTU4LCJleHAiOjE3NjEyMTE3NTh9.55tfUrP-9XhdiJSWn06u7uWxCwsUi0DLZnKgeWlZO5s; Max-Age=3600; Expires=Thu, 23 Oct 2025 09:29:18 GMT; Path=/; HttpOnly

### List all notes
GET http://localhost:3000/notes
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYxMjA4MTU4LCJleHAiOjE3NjEyMTE3NTh9.55tfUrP-9XhdiJSWn06u7uWxCwsUi0DLZnKgeWlZO5s; Max-Age=3600; Expires=Thu, 23 Oct 2025 09:29:18 GMT; Path=/; HttpOnly

### Update note content
PATCH http://localhost:3000/notes/29
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYxMjA4MTU4LCJleHAiOjE3NjEyMTE3NTh9.55tfUrP-9XhdiJSWn06u7uWxCwsUi0DLZnKgeWlZO5s; Max-Age=3600; Expires=Thu, 23 Oct 2025 09:29:18 GMT; Path=/; HttpOnly

{
    "content": "This is a test note content 1231231 312 3213123 13."
}

### Delete a note
DELETE http://localhost:3000/notes/30
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYxMjA4MTU4LCJleHAiOjE3NjEyMTE3NTh9.55tfUrP-9XhdiJSWn06u7uWxCwsUi0DLZnKgeWlZO5s; Max-Age=3600; Expires=Thu, 23 Oct 2025 09:29:18 GMT; Path=/; HttpOnly