### Create a new note
POST http://localhost:3000/notes
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYyOTQyNjMwLCJleHAiOjE3NjI5Nzg2MzB9.JzczM2R__a46LXT80tleTXEgPDgkqR_hHTtF0uRu6RA; Max-Age=36000; Expires=Wed, 12 Nov 2025 20:17:10 GMT; Path=/; HttpOnly

{
    "name": "polska_chrzest_966",
    "content": "Chrzest Polski miał miejsce w 966 roku i jest uznawany za jedno z najważniejszych wydarzeń w historii naszego kraju. Książę Mieszko I, władca Polan, przyjął chrzest prawdopodobnie z rąk czeskich duchownych, co oznaczało początek chrystianizacji ziem polskich. Wydarzenie to włączyło Polskę w krąg kultury zachodnioeuropejskiej, umocniło pozycję Mieszka I na arenie międzynarodowej i przyczyniło się do powstania zorganizowanego państwa. Chrzest Polski miał więc nie tylko znaczenie religijne, ale także polityczne i kulturowe."
}

### Download note content
GET http://localhost:3000/notes/29
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYxMjA4MTU4LCJleHAiOjE3NjEyMTE3NTh9.55tfUrP-9XhdiJSWn06u7uWxCwsUi0DLZnKgeWlZO5s; Max-Age=3600; Expires=Thu, 23 Oct 2025 09:29:18 GMT; Path=/; HttpOnly

### List all notes
GET http://localhost:3000/notes
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYxMjA4MTU4LCJleHAiOjE3NjEyMTE3NTh9.55tfUrP-9XhdiJSWn06u7uWxCwsUi0DLZnKgeWlZO5s; Max-Age=3600; Expires=Thu, 23 Oct 2025 09:29:18 GMT; Path=/; HttpOnly

### Update note content
PATCH http://localhost:3000/notes/29
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYxMjA4MTU4LCJleHAiOjE3NjEyMTE3NTh9.55tfUrP-9XhdiJSWn06u7uWxCwsUi0DLZnKgeWlZO5s; Max-Age=3600; Expires=Thu, 23 Oct 2025 09:29:18 GMT; Path=/; HttpOnly

{
    "content": "This is a test note content 1231231 312 3213123 13."
}

### Delete a note
DELETE http://localhost:3000/notes/30
Content-Type: application/json
Cookie: COWRITE_SESSION_ID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOjQsXCJlbWFpbFwiOlwidGVzdHVzZXIxdzJcIixcInVzZXJuYW1lXCI6XCJ0ZXN0MXcyQGV4YW1wbGUuY29tXCJ9IiwiaWF0IjoxNzYxMjA4MTU4LCJleHAiOjE3NjEyMTE3NTh9.55tfUrP-9XhdiJSWn06u7uWxCwsUi0DLZnKgeWlZO5s; Max-Age=3600; Expires=Thu, 23 Oct 2025 09:29:18 GMT; Path=/; HttpOnly