### Create a new note
POST http://localhost:3000/notes
Content-Type: application/json
Cookie: 

{
    "name": "te2",
    "content": "This is a test note content."
}

### Download note content
GET http://localhost:3000/notes/29
Content-Type: application/json
Cookie: 

### List all notes
GET http://localhost:3000/notes
Content-Type: application/json
Cookie: 

### Update note content
PATCH http://localhost:3000/notes/29
Content-Type: application/json
Cookie: 

{
    "content": "This is a test note content 1231231 312 3213123 13."
}